### ISSUE TITLE
Following the README does not lead to succesful display of the GUI on linux

### ISSUE THREAD

**Issue by Bachibouzouk** [architecture-building-systems/CityEnergyAnalyst-GUI#40]
Hello,

I wanted to checkout your project because the video on the website looked amazing. Unfortunately I was not able to do so under Ubuntu. I cloned the repo (`git clone https://github.com/architecture-building-systems/CityEnergyAnalyst-GUI.git` instead of `git clone https://github.com/architecture-building-systems/cea-electron.git` as I believe this was a previous version?) and installed the dependencies with `yarn` 

I then ran `yarn dev` but I got the following error:

```
  ERROR in ./src/renderer/components/InputEditor/InputEditor.js
  Module not found: Error: Can't resolve './InputEditor.css' in '~/CityEnergyAnalyst-GUI/src/renderer/components/InputEditor'
   @ ./src/renderer/components/InputEditor/InputEditor.js 16:0-27
   @ ./src/renderer/containers/HomePage.js
   @ ./src/renderer/containers/App.js
   @ ./src/renderer/index.js
   @ multi react-hot-loader/patch css-hot-loader/hotModuleReplacement ./src/renderer/index.js
  
  ERROR in ./src/renderer/components/HomePage/Header.js
  Module not found: Error: Can't resolve './Searchbar' in '~/CityEnergyAnalyst-GUI/src/renderer/components/HomePage'
   @ ./src/renderer/components/HomePage/Header.js 7:0-36 59:38-47
   @ ./src/renderer/containers/HomePage.js
   @ ./src/renderer/containers/App.js
   @ ./src/renderer/index.js
   @ multi react-hot-loader/patch css-hot-loader/hotModuleReplacement ./src/renderer/index.js
```

I noticed this were typos: 
- the file in the repo is `inputEditor.css` instead of `InputEditor.css`
- `SearchBar` should be imported instead of `Searchbar`

I fixed the typos and then `yarn dev` said that the Renderer had `Compiled successfully.`

I saw the app loading window but then nothing happened and this was the output in my terminal

```
┏ Electron -------------------

  No Response

┗ ----------------------------
┏ Electron -------------------

  (node:3783) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stdout' of undefined
      at createCEAProcess (webpack-internal:///./src/main/ceaProcess.js:30:7)
      at eval (webpack-internal:///./src/main/index.js:95:123)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)

┗ ----------------------------
┏ Electron -------------------

  (node:3783) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

┗ ----------------------------
┏ Electron -------------------

  (node:3783) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

┗ ----------------------------

```

maybe it is related to a missing installation the the cea package? I will look into this but I wanted to notify the typos in the filenames at least. Any help or hint would be welcome! Thanks a lot in advance!

My distribution is Ubuntu 18.04.5 LTS
Here is the console output of the `yarn` command

```
yarn install v1.22.5
[1/5] Resolving packages...
[2/5] Fetching packages...
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/5] Linking dependencies...
warning " > @handsontable/react@3.1.3" has incorrect peer dependency "handsontable@>=7.2.2".
warning " > connected-react-router@6.8.0" has unmet peer dependency "immutable@^3.8.1 || ^4.0.0-rc.1".
warning " > connected-react-router@6.8.0" has unmet peer dependency "seamless-immutable@^7.1.3".
warning " > frameless-titlebar@1.0.8" has unmet peer dependency "prop-types@^15.5.4".
warning " > nebula.gl@0.15.0" has unmet peer dependency "@deck.gl/core@^7.0.0".
warning " > nebula.gl@0.15.0" has unmet peer dependency "@deck.gl/layers@^7.0.0".
warning " > nebula.gl@0.15.0" has unmet peer dependency "@luma.gl/constants@^7.0.0".
warning " > nebula.gl@0.15.0" has unmet peer dependency "@luma.gl/core@^7.0.0".
warning "nebula.gl > @nebula.gl/layers@0.15.0" has unmet peer dependency "@deck.gl/core@^7.0.0".
warning "nebula.gl > @nebula.gl/layers@0.15.0" has unmet peer dependency "@deck.gl/layers@^7.0.0".
warning "nebula.gl > @nebula.gl/layers@0.15.0" has unmet peer dependency "@luma.gl/core@^7.0.0".
warning " > react-hot-loader@4.12.20" has unmet peer dependency "@types/react@^15.0.0 || ^16.0.0".
warning " > @babel/plugin-proposal-class-properties@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/plugin-proposal-class-properties > @babel/helper-create-class-features-plugin@7.9.5" has unmet peer dependency "@babel/core@^7.0.0".
warning " > @babel/plugin-proposal-optional-chaining@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/plugin-proposal-optional-chaining > @babel/plugin-syntax-optional-chaining@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @babel/preset-react@7.9.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-react > @babel/plugin-transform-react-display-name@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-react > @babel/plugin-transform-react-jsx@7.9.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-react > @babel/plugin-transform-react-jsx-development@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-react > @babel/plugin-transform-react-jsx-self@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-react > @babel/plugin-transform-react-jsx-source@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-react > @babel/plugin-transform-react-jsx > @babel/plugin-syntax-jsx@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
[4/5] Building fresh packages...
[5/5] Cleaning modules...
Done in 368.85s.
```

**Comment by Bachibouzouk** [comment]
@reyery , @daren-thomas, sorry to bother you but would you have any hint/idea on this issue?

**Comment by reyery** [comment]
@Bachibouzouk sorry for the late response. Thanks for your interest in the project! However this repo only contains the GUI for CityEnergyAnalyst and does not install the actual package needed to run simulations. Furthermore, the GUI has not been properly tested with Linux, so it might not work well on Ubuntu. You could checkout the main repo of the project [here](https://github.com/architecture-building-systems/CityEnergyAnalyst) instead (we have solutions to run CEA in Linux but only with the command line interface).

**Comment by Bachibouzouk** [comment]
Thanks for your answer @reyery :) I will see if installing the package solves the problem and let you know if I am successful!
